-- Wick's Gear
-- DataSetBonus.lua: generated by WickSuite/tools/emit-gear-data.py on 2026-09-23.
-- Do not edit. Re-run the scrapers and then this.
--
-- Classic's set bonuses, not Forever's. Forever publishes none:
-- its set tooltip carries the name and nothing else. These are the
-- same sets carried forward, so Classic is the best source there
-- is, but Forever has retuned things Classic had before, so the
-- addon shows them as a guide and says where they came from.

local ADDON, ns = ...
if not WickCore then return end   -- said once in Core.lua

ns.SET_BONUS_APPROXIMATE = true
ns.SET_BONUS = {
    ["Battlegear of Heroism"] = {
        { pieces = 2, text = "+40 Attack Power." },
        { pieces = 4, text = "Chance on melee attack to heal you for 88 to 132 and energize you for 10 Rage" },
        { pieces = 6, text = "+8 All Resistances." },
        { pieces = 8, text = "+200 Armor." },
    },
    ["Battlegear of Valor"] = {
        { pieces = 2, text = "+200 Armor." },
        { pieces = 4, text = "+40 Attack Power." },
        { pieces = 6, text = "Chance on melee attack to heal you for 88 to 132 and energize you for 10 Rage" },
        { pieces = 8, text = "+8 All Resistances." },
    },
    ["Beastmaster Armor"] = {
        { pieces = 2, text = "+40 Attack Power." },
        { pieces = 4, text = "Your melee and ranged autoattacks have a 6% chance to energize you for 300 mana." },
        { pieces = 6, text = "+8 All Resistances." },
        { pieces = 8, text = "+200 Armor." },
    },
    ["Beaststalker Armor"] = {
        { pieces = 2, text = "+200 Armor." },
        { pieces = 4, text = "+40 Attack Power." },
        { pieces = 6, text = "Your melee and ranged autoattacks have a 6% chance to energize you for 300 mana." },
        { pieces = 8, text = "+8 All Resistances." },
    },
    ["Black Dragon Mail"] = {
        { pieces = 2, text = "Improves your chance to hit with all spells and attacks by 1%." },
        { pieces = 3, text = "Improves your chance to get a critical strike with all spells and attacks by 2%." },
        { pieces = 4, text = "+10 Fire Resistance." },
    },
    ["Blood Tiger Harness"] = {
        { pieces = 2, text = "Improves your chance to get a critical strike by 1%." },
        { pieces = 2, text = "Improves your chance to get a critical strike with spells by 1%." },
    },
    ["Bloodsoul Embrace"] = {
        { pieces = 3, text = "Restores 12 mana per 5 sec." },
    },
    ["Bloodvine Garb"] = {
        { pieces = 3, text = "Improves your chance to get a critical strike with spells by 2%." },
    },
    ["Blue Dragon Mail"] = {
        { pieces = 2, text = "+4 All Resistances." },
        { pieces = 3, text = "Increases damage and healing done by magical spells and effects by up to 28." },
    },
    ["Chain of the Scarlet Crusade"] = {
        { pieces = 2, text = "+10 Armor." },
        { pieces = 3, text = "Increased Defense +1." },
        { pieces = 4, text = "+5 Shadow Resistance." },
        { pieces = 5, text = "+15 Attack Power when fighting Undead." },
        { pieces = 6, text = "Improves your chance to hit by 1%." },
    },
    ["Darkmantle Armor"] = {
        { pieces = 2, text = "+40 Attack Power." },
        { pieces = 4, text = "Chance on melee attack to restore 35 energy." },
        { pieces = 6, text = "+8 All Resistances." },
        { pieces = 8, text = "+200 Armor." },
    },
    ["Deathbone Guardian"] = {
        { pieces = 2, text = "Increased Defense +3." },
        { pieces = 3, text = "+50 Armor." },
        { pieces = 4, text = "+15 All Resistances." },
        { pieces = 5, text = "Increases your chance to parry an attack by 1%." },
    },
    ["Deathmist Raiment"] = {
        { pieces = 2, text = "Increases damage and healing done by magical spells and effects by up to 23." },
        { pieces = 4, text = "Your melee autoattacks and spellcasts have a 6% chance to heal you for 270 to 330 health." },
        { pieces = 6, text = "+8 All Resistances." },
        { pieces = 8, text = "+200 Armor." },
    },
    ["Defias Leather"] = {
        { pieces = 2, text = "+10 Armor." },
        { pieces = 3, text = "+5 Arcane Resistance." },
        { pieces = 4, text = "Increased Daggers +1." },
        { pieces = 5, text = "+10 Attack Power." },
    },
    ["Devilsaur Armor"] = {
        { pieces = 2, text = "+10 Fire Resistance." },
        { pieces = 2, text = "Improves your chance to hit with all spells and attacks by 2%." },
    },
    ["Dreadmist Raiment"] = {
        { pieces = 2, text = "+200 Armor." },
        { pieces = 4, text = "Increases damage and healing done by magical spells and effects by up to 23." },
        { pieces = 6, text = "Your melee autoattacks and spellcasts have a 6% chance to heal you for 270 to 330 health." },
        { pieces = 8, text = "+8 All Resistances." },
    },
    ["Embrace of the Viper"] = {
        { pieces = 2, text = "Increases damage done by Nature spells and effects by up to 7." },
        { pieces = 3, text = "Increased Staves +2." },
        { pieces = 4, text = "Increases healing done by spells and effects by up to 11." },
        { pieces = 5, text = "+10 Intellect." },
    },
    ["Feralheart Raiment"] = {
        { pieces = 2, text = "+40 Attack Power, up to 23 increased damage from spells, and up to 44 increased healing from spells." },
        { pieces = 4, text = "2% chance on spellcast to energize you for 300 mana, 6% chance on dealing a melee autoattack to energize you for 40 Energy, and 3% chance on being hit by a melee attack to energize you for 10 Rage." },
        { pieces = 6, text = "+8 All Resistances." },
        { pieces = 8, text = "+200 Armor." },
    },
    ["Green Dragon Mail"] = {
        { pieces = 2, text = "Restores 3 mana per 5 sec." },
        { pieces = 3, text = "Allows 15% of your Mana regeneration to continue while casting." },
    },
    ["Imperial Plate"] = {
        { pieces = 2, text = "+100 Armor." },
        { pieces = 4, text = "+28 Attack Power." },
        { pieces = 6, text = "+18 Stamina." },
    },
    ["Ironfeather Armor"] = {
        { pieces = 2, text = "Increases damage and healing done by magical spells and effects by up to 20." },
    },
    ["Lightforge Armor"] = {
        { pieces = 2, text = "+200 Armor." },
        { pieces = 4, text = "+40 Attack Power and up to 40 increased healing from spells." },
        { pieces = 6, text = "6% chance on melee autoattack and 4% chance on spellcast to increase your damage and healing done by magical spells and effects by up to 95 for 10 sec." },
        { pieces = 8, text = "+8 All Resistances." },
    },
    ["Magister's Regalia"] = {
        { pieces = 2, text = "+200 Armor." },
        { pieces = 4, text = "Increases damage and healing done by magical spells and effects by up to 23." },
        { pieces = 6, text = "Your spellcasts have a 6% chance to energize you for 300 mana." },
        { pieces = 8, text = "+8 All Resistances." },
    },
    ["Primal Batskin"] = {
        { pieces = 3, text = "Minor increase to running and swimming speed." },
    },
    ["Shadowcraft Armor"] = {
        { pieces = 2, text = "+200 Armor." },
        { pieces = 4, text = "+40 Attack Power." },
        { pieces = 6, text = "Chance on melee attack to restore 35 energy." },
        { pieces = 8, text = "+8 All Resistances." },
    },
    ["Sorcerer's Regalia"] = {
        { pieces = 2, text = "Increases damage and healing done by magical spells and effects by up to 23." },
        { pieces = 4, text = "Your spellcasts have a 6% chance to energize you for 300 mana." },
        { pieces = 6, text = "+8 All Resistances." },
        { pieces = 8, text = "+200 Armor." },
    },
    ["Stormshroud Armor"] = {
        { pieces = 2, text = "5% chance of dealing 15 to 25 Nature damage on a successful melee attack." },
        { pieces = 3, text = "2% chance on melee attack of restoring 30 energy." },
        { pieces = 4, text = "+14 Attack Power." },
    },
    ["The Darksoul"] = {
        { pieces = 3, text = "Increased Defense +20." },
    },
    ["The Elements"] = {
        { pieces = 2, text = "+200 Armor." },
        { pieces = 4, text = "Increases damage and healing done by magical spells and effects by up to 23." },
        { pieces = 6, text = "Chance on spell cast to increase your damage and healing by up to 95 for 10 sec." },
        { pieces = 8, text = "+8 All Resistances." },
    },
    ["The Five Thunders"] = {
        { pieces = 2, text = "+40 Attack Power, up to 23 increased damage from spells, and up to 44 increased healing from spells." },
        { pieces = 4, text = "6% chance on mainhand autoattack and 4% chance on spellcast to increase your damage and healing done by magical spells and effects by up to 95 for 10 sec." },
        { pieces = 6, text = "+8 All Resistances." },
        { pieces = 8, text = "+200 Armor." },
    },
    ["The Gladiator"] = {
        { pieces = 2, text = "+20 Armor." },
        { pieces = 3, text = "Increased Defense +2." },
        { pieces = 4, text = "+10 Attack Power." },
        { pieces = 5, text = "Improves your chance to get a critical strike by 1%." },
    },
    ["Vestments of the Devout"] = {
        { pieces = 2, text = "+200 Armor." },
        { pieces = 4, text = "Increases damage and healing done by magical spells and effects by up to 23." },
        { pieces = 6, text = "Your spellcasts have a 6% chance to energize you for 300 mana." },
        { pieces = 8, text = "+8 All Resistances." },
    },
    ["Vestments of the Virtuous"] = {
        { pieces = 2, text = "Increases damage and healing done by magical spells and effects by up to 23." },
        { pieces = 4, text = "Your spellcasts have a 6% chance to energize you for 300 mana." },
        { pieces = 6, text = "+8 All Resistances." },
        { pieces = 8, text = "+200 Armor." },
    },
    ["Volcanic Armor"] = {
        { pieces = 3, text = "5% chance of dealing 15 to 25 Fire damage on a successful melee attack." },
    },
    ["Wildheart Raiment"] = {
        { pieces = 2, text = "+200 Armor." },
        { pieces = 4, text = "+40 Attack Power, up to 23 increased damage from spells, and up to 44 increased healing from spells." },
        { pieces = 6, text = "2% chance on spellcast to energize you for 300 mana, 6% chance on dealing a melee autoattack to energize you for 40 Energy, and 3% chance on being hit by a melee attack to energize you for 10 Rage." },
        { pieces = 8, text = "+8 All Resistances." },
    },
}
